
Kayjax={requests:[],maxCount:10,onStop:function(){},onSend:function(){},onStart:function(){},onReceive:function(){},appendQuery:function(url,query){},fireEndEvents:function(){if(typeof Kayjax.onReceive==="function"){try{Kayjax.onReceive();}catch(e){}}
if(Kayjax.requests.length===0&&typeof Kayjax.onStop==="function"){try{Kayjax.onStop();}catch(e){}}},fireStartEvents:function(){if(Kayjax.requests.length===0&&typeof Kayjax.onStart==="function"){try{Kayjax.onStart();}catch(e){}}
if(typeof Kayjax.onSend==="function"){try{Kayjax.onSend();}catch(e){}}},getReasonFromResponseCode:function(code){var reason="OK";if(code>=300){if(code<400){reason="The server attempted to redirect the request.";}else if(code<500){reason="Invalid request or access denied.";}else if(code<600){reason="Internal server error.";}else{reason="An unspecified HTTP error occurred.";}}
return reason;},resolveUrl:function(url){var rootExp=/^~\//;if(rootExp.test(url)){if(typeof Kayjax.appPath==="string"){if(!/\/$/.test(Kayjax.appPath)){Kayjax.appPath=Kayjax.appPath+"/";}}else{Kayjax.appPath="/";}
url=url.replace(rootExp,Kayjax.appPath);}
return url;},request:function(url,options){},response:function(transport,jsonEvaluator){var obj,queued,newQueue,i,n,id,resp,text;newQueue=[];id=transport.getResponseHeader("X-Response-Id");resp={success:true,reason:"",value:null};text=transport.responseText||"";try{obj=jsonEvaluator(text.replaceJSONDates());resp.success=obj.success;resp.reason=obj.reason;resp.value=obj.value;}catch(e){resp.success=false;resp.reason="An invalid response was received from the server.";}
if(!resp.success&&!resp.reason){resp.reason=Kayjax.getReasonFromResponseCode(transport.status);}
for(i=0,n=Kayjax.requests.length;i<n;i++){if(Kayjax.requests[i].id.toString()===id){queued=Kayjax.requests[i];}else{newQueue.push(Kayjax.requests[i]);}}
Kayjax.requests=newQueue;if(queued){if(typeof queued.callback==="function"){queued.callback(resp);}}else{if(!resp.success){alert(resp.reason);}}
Kayjax.fireEndEvents();return resp;},update:function(element,url,options){},updateResponse:function(transport,element){var id,queued,newQueue,resp,i,n;id=transport.getResponseHeader("X-Response-Id");newQueue=[];resp={success:true,reason:"",value:""};if(transport.status!==0&&!(transport.status>=200&&transport.status<300)){resp.success=false;resp.reason=Kayjax.getReasonFromResponseCode(transport.status);}else{resp.value=transport.responseText||"";}
for(i=0,n=Kayjax.requests.length;i<n;i++){if(Kayjax.requests[i].id.toString()===id){queued=Kayjax.requests[i];}else{newQueue.push(Kayjax.requests[i]);}}
Kayjax.requests=newQueue;if(typeof element==="string"){element=document.getElementById(element);}
element.innerHTML=resp.value;if(queued){if(typeof queued.callback==="function"){queued.callback(resp);}}else{if(!resp.success){alert(resp.reason);}}
Kayjax.fireEndEvents();return resp;}};Date.prototype.toJson=function(){return'"\\\/Date('+this.getTime()+')\\\/"';};Date.prototype.toShortDateString=function(format,separator){format=format||"ymd";separator=separator||"-";var year=this.getFullYear();var month=this.getMonth()+1;var date=this.getDate();if(month<10)month="0"+month;if(date<10)date="0"+date;switch(format){case("mdy"):return month+separator+date+separator+year;case("dmy"):return date+separator+month+separator+year;default:return year+separator+month+separator+date;}};Date.prototype.toShortTimeString=function(){var hours=this.getHours();var minutes=this.getMinutes();var ampm=hours<12?"AM":"PM";if(hours==0){hours=12;}else if(hours>12){hours-=12;}
if(minutes<10){minutes="0"+minutes;}
return hours+":"+minutes+" "+ampm;};Date.fromJson=function(json){return typeof json==="string"&&json.isJsonDate()?eval(json.replace(String.DATE_EXP,"new Date($1)")):NaN;};String.prototype.camel=function(){var matches=/^([A-Z])/.exec(this);if(matches){return matches[1].toLowerCase()+this.substr(1);}else{return this;}};String.prototype.getUrlScheme=function(){var scheme="";var match=/^([^:]+)/.exec(this);if(match&&match.length>1){scheme=match[1];}
return scheme;};String.prototype.isJsonDate=function(){return this.match(String.DATE_EXP);};String.prototype.replaceJSONDates=function(){return this.replace(/"\\\/Date\(([\d\-]+)\)\\\/"/g,"new Date($1)");};String.prototype.trim=function(){return this.replace(/^\s+/g,'').replace(/\s+$/g,'');};String.DATE_EXP=(/^\/Date\(([\d-]+)\)\/$/);
Object.extend(Kayjax,{appendQuery:function(url,query){var q=(url.indexOf("?")>=0)?url.parseQuery():{};Object.extend(q,(Object.isString(query)?query.parseQuery():{}));query=Object.toQueryString(q);return url.split("?")[0]+(query?"?"+query:"");},request:function(url,options){if(Kayjax.requests.length>=Kayjax.maxCount){setTimeout(Kayjax.request.curry(url,options),100);}else{Kayjax.fireStartEvents();options=options||{};var queued,postBody,params,req;queued={id:Kayjax.requests.length,callback:options.callback||null};Kayjax.requests.push(queued);postBody=options.parameters?Object.toJSON(options.parameters):"";params={requestHeaders:["X-Request-Id",queued.id],contentType:"application/json",postBody:postBody,asynchronous:(Object.isFunction(queued.callback))?true:false};if(params.asynchronous){params.onComplete=function(transport){Kayjax.response(transport,function(json){return eval('('+json.unfilterJSON()+')');});};}
req=new Ajax.Request(Kayjax.appendQuery(Kayjax.resolveUrl(url),options.query),params);if(!params.asynchronous){return Kayjax.response(new Ajax.Response(req));}}},update:function(element,url,options){if(Kayjax.requests.length>=Kayjax.maxCount){setTimeout(Kayjax.requests.curry(element,url,options),100);}else{Kayjax.fireStartEvents();options=options||{};var queued,params;queued={id:Kayjax.requests.length,callback:options.callback||null};Kayjax.requests.push(queued);params={requestHeaders:["X-Request-Id",queued.id],asynchronous:true,postBody:options.postBody,onComplete:function(transport){Kayjax.updateResponse(transport,element);}};new Ajax.Request(Kayjax.appendQuery(Kayjax.resolveUrl(url),options.query),params);}}});